/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-error-container": "#93000a",
        "secondary": "#9d4300",
        "surface-bright": "#f8f9ff",
        "on-tertiary-container": "#3fd298",
        "tertiary": "#003d27",
        "on-surface": "#151c25",
        "on-primary-fixed": "#001453",
        "primary": "#00288e",
        "on-primary-fixed-variant": "#173bab",
        "error": "#ba1a1a",
        "on-primary-container": "#a8b8ff",
        "primary-container": "#1e40af",
        "surface": "#f8f9ff",
        "on-primary": "#ffffff",
        "inverse-primary": "#b8c4ff",
        "on-secondary": "#ffffff",
        "inverse-on-surface": "#eaf1fe",
        "surface-variant": "#dce3f0",
        "surface-container": "#e7eefb",
        "surface-dim": "#d4dae7",
        "outline": "#757684",
        "on-background": "#151c25",
        "on-error": "#ffffff",
        "primary-fixed": "#dde1ff",
        "on-tertiary-fixed": "#002113",
        "secondary-fixed-dim": "#ffb690",
        "tertiary-fixed": "#6ffbbe",
        "on-surface-variant": "#444653",
        "surface-container-lowest": "#ffffff",
        "surface-container-highest": "#dce3f0",
        "tertiary-container": "#00563a",
        "on-secondary-fixed-variant": "#783200",
        "on-tertiary-fixed-variant": "#005236",
        "surface-container-low": "#eef4ff",
        "on-secondary-fixed": "#341100",
        "on-secondary-container": "#5c2400",
        "background": "#f8f9ff",
        "error-container": "#ffdad6",
        "surface-tint": "#3755c3",
        "on-tertiary": "#ffffff",
        "primary-fixed-dim": "#b8c4ff",
        "tertiary-fixed-dim": "#4edea3",
        "outline-variant": "#c4c5d5",
        "inverse-surface": "#2a313b",
        "secondary-fixed": "#ffdbca",
        "surface-container-high": "#e2e8f5",
        "secondary-container": "#fd761a"
      },
      fontFamily: {
        "headline": ["Plus Jakarta Sans", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "1rem",
        "lg": "2rem",
        "xl": "3rem",
        "full": "9999px"
      },
    },
  },
  plugins: [],
}
